### ISSUE TITLE
Migration is not applied, however migration message is printed

### ISSUE THREAD

**Issue by kvelaro** [golang-migrate/migrate#1170]
**Describe the Bug**
MIgration is applied, actual statements are not executed

**Steps to Reproduce**
1. docker-compose.yml
```
  migrate:
    image: migrate/migrate
    networks:
      - example
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - "/migrations:/migrations" #???
    command: ["-path", "/migrations", "-database",  "postgres://example:example@postgresdb:5432/postgresql?sslmode=disable", "up"]
    depends_on:
      - postgresdb
```

```
example-migrate-1  | 1/u main_tables (12.982886ms)
example-migrate-1 exited with code 0
```

```
1726763207_main.up.sql

CREATE TABLE IF NOT EXISTS text (
    id BIGSERIAL PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id),
    text VARCHAR(4096)
);

```

```
             List of relations
 Schema |       Name        | Type  | Owner 
--------+-------------------+-------+-------
 public | schema_migrations | table | nashi
(1 row)

```

**Expected Behavior**
All statements are applied (tables created)

**Migrate Version**
docker image (latest)

**Loaded Source Drivers**
as specified in docker-compose (file)

**Loaded Database Drivers**
as specified in docker-compose (postgres)
