### ISSUE TITLE
database: no scheme while running in docker

### ISSUE THREAD

**Issue by jney** [golang-migrate/migrate#133]
Hey guys. Using migrate with `docker-compose` with the following configuration

```yml
version: "3"

services:
  migrate:
    image: migrate/migrate
    environment:
      DATABASE_URL: postgres://docker:docker@postgres/publisher/db
    command: ["-database", "$${DATABASE_URL}", "-path", "/migrations", "up"]
    volumes:
      - $PWD/database/migrations:/migrations
    depends_on:
      - postgres
```

gives me the following error:

```
error: database: no scheme
```

I checked the folded is mounted correctly, doing:

```sh
docker-compose run --entrypoint="" migrate ls /migrations
```

and everything looks fine to me. any idea?
