### ISSUE TITLE
cassandra: concurrency problem (column family ID mismatch)

### ISSUE THREAD

**Issue by huttotw** [golang-migrate/migrate#249]
**Describe the Bug**
When running a migration concurrently (many containers containers deploying at the same time), the migration fails with `column family mismatch`. I believe this is because each container is trying to create a table at the same time and the metadata is not being propagated fast enough for each node to realize the table already exists.

**Steps to Reproduce**
1. My migrations look like
```
CREATE TABLE IF NOT EXISTS example.hello_world (
    name TEXT,
    greeting TEXT,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS example.hello_world_2 (
    name TEXT,
    greeting TEXT,
    PRIMARY KEY (name)
);
```
2. I ran migrate with the following options:
```
&migrateCassandra.Config{
    KeyspaceName:          "example",
    MultiStatementEnabled: true,
}
```
3. See error:
```
java.lang.RuntimeException:
java.util.concurrent.ExecutionException: 
    java.lang.RuntimeException:      
        org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found e8c03790-c952-11e4-a753-5981ea73cd7c; expected e8b14370-c952-11e4-a844-8f10bfb9c386)
```

**Expected Behavior**
I would expect the Lock and Unlock functions in `database/cassandra/cassandra.go` to check a `schema_locks` table using the  `All` consistency level, and only run migrations when it can acquire a lock.

**Migrate Version**
master

**Loaded Source Drivers**
file

**Loaded Database Drivers**
cassandra

**Go Version**
golang:1.12 image

**Stacktrace**
Please provide if available

**Additional context**
