### ISSUE TITLE
Getting EOF on Alpine Image and Verbose isn't helpful

### ISSUE THREAD

**Issue by euannliu** [golang-migrate/migrate#457]
Creating a job on Gitlab with `alpine:latest` and used curl to pull the exec. I ran migration and ran into an EOF error for which when I run `migrate` on my local machine (Mac OS) it does not produce an EOF error.

`curl -L https://github.com/golang-migrate/migrate/releases/download/v4.13.0/migrate.linux-amd64.tar.gz`

`$ ./migrate.linux-amd64 -path ${PATH} -database "${DATABASE}" up
error: EOF`

`$ ./migrate.linux-amd64 -verbose -path ${PATH} -database "${DATABASE}" up
2020/10/12 23:39:02 error: EOF`

Anyone have any ideas?

**Comment by Nuboskill** [comment]
I've got it in CI too.
```
[mysql] 2020/10/14 01:26:55 packets.go:36: unexpected EOF
[mysql] 2020/10/14 01:26:55 packets.go:36: unexpected EOF
[mysql] 2020/10/14 01:26:55 packets.go:36: unexpected EOF
error: driver: bad connection
```

**Comment by emarais-godaddy** [comment]
I ran into this as well where the migrator tries to run before the server has started. I added a health check to my mysql service and that forces the github action to wait until the server is up.

ex:

```
jobs:
  coverage:
    name: coverage report
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: <...>
          MYSQL_DATABASE: <...>
```
