### ISSUE TITLE
Migrations for mongo db not run. auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.

### ISSUE THREAD

**Issue by IaroslavKorobeinikov** [golang-migrate/migrate#545]
**Describe the Bug**
Cannot run migration for mongodb for some reason

**Steps to Reproduce**
I have docker-compose for run mongo:
```yml
version: '3'

services:
  mongo_db:
    image: mongo:4.4-bionic
    container_name: auth-mongo-db
    restart: always
    ports:
      - 0.0.0.0:27017:27017
    environment:
      MONGO_INITDB_DATABASE: auth_microservice_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
```
1. I just up mongo in docker through docker-compose up -d
2. When iI try to run migration like
```sh
migrate -database "mongodb://root:root@127.0.0.1:27017/auth_microservice_db" -path db/migrations up
```
I have error:
> error: connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.

It's strange because at the same time my go application use same connection and works perfect 
```golang
func NewMongoClient(cfg config.Config) *mongo.Client {
	log.Info("[GetMongoClient] Initialize mongo client")
	client, err := mongo.NewClient(options.Client().ApplyURI("mongodb://root:root@127.0.0.1:27017"))

	if err != nil {
		log.Fatalf("[GetMongoClient.NewClient] Error while try to initialize mongo db %v", err)
	}

	// Create connect
	err = client.Connect(context.TODO())
	if err != nil {
		log.Fatalf("[GetMongoClient.Connect] Error while connect to mongodb %v", err)
	}

	// Check the connection
	err = client.Ping(context.TODO(), nil)
	if err != nil {
		log.Fatalf("[GetMongoClient.Ping] Error while ping to mongodb %v", err)
	}
	return client
}
```
This no occured some errors

And request to db through collection not occured any errors at the same time
```golang
func NewUserRepository(shared settings.Shared, client *mongo.Client) UserRepository {
	collection := client.Database("auth_microservice_db").Collection("users")

	return userRepository{
		collection: collection,
		shared:     shared,
	}
}
```

**Expected Behavior**
Migrations for mongodb should run without errors

**Migrate Version**
dev (for some reason?)
> I install migrate with this command
```sh
go get -tags 'mongodb' -u github.com/golang-migrate/migrate/v4/cmd/migrate/
```

**Loaded Source Drivers**
file

**Loaded Database Drivers**
Database drivers: mongodb, mongodb+srv, stub

**Go Version**
go version go1.14.15 linux/amd64

**Stacktrace**
```
error: connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
```
