### ISSUE TITLE
Getting "error: file does not exist"  

### ISSUE THREAD

**Issue by nutmix** [golang-migrate/migrate#79]
We have run the migration successfully, and now i need to run it again in case there are any new migrations.

This is he command we are using:

migrate -database 'mysql://xxx:yyyy@/zzzz' -source file://go/src/github.com/me/myproj.org/db/schema up

I am in the root directory of the user (i.e. /home/myuser), and underneath is the structure:
go/src/github.com/me/myproj.org/db/schema which contains files like:

201802221525_init_schema.down.sql  201805211743_us_states.down.sql  201805291420_countries.down.sql  201806051200_currencies.down.sql
201802221525_init_schema.up.sql    201805211743_us_states.up.sql    201805291420_countries.up.sql    201806051200_currencies.up.sql
etc.

We see that with mattes migrate, there were many similar issues with no obvious resolution.

in the db in schema_migrations table, I see it says version 201807191200, although i am not sure this has any bearing on the issue.

If I change the file path to something which doesn't exist, e.g.

migrate -database 'mysql://xxx:yyyy@/zzzz' -source file://go/src/github.com/me/myproj.org/notexist up

I get a different error message:

error: open /home/muyuser/go/src/github.com/me/myproj.org/notexist : no such file or directory

This is how we installed migrate:

wget https://github.com/golang-migrate/migrate/releases/download/v3.2.0/migrate.linux-amd64.tar.gz 
gunzip migrate.linux-amd64.tar.gz 
tar xvf migrate.linux-amd64.tar
mv migrate.linux-amd64 /usr/bin/migrate

**Comment by nutmix** [comment]
This error might be occurring when the DB is up to date, i.e. no migrations needed.  However, if so, its still a bug as it should say up to date, not error.

**Comment by dotchev** [comment]
If it is up to date, you will get a different error - "no change".

I get "file does not exist" error when I accidentally delete some of my migration scripts, e.g. switching between git branches.
Here is an example with some added trace messages:
```
versionExists: version 2
versionExists: ReadUp error: read version 2 .../storage/postgres/migrations: file does not exist
versionExists: ReadDown error: read version 2 .../storage/postgres/migrations: file does not exist
versionExists: fallthrough - os.ErrNotExist
PANI[0000] file does not exist 
```
But in that directory there are scripts only for version 1
```
$ ls storage/postgres/migrations
001_initial_schema.down.sql
001_initial_schema.up.sql
```
During debugging I see [versionExists](https://github.com/golang-migrate/migrate/blob/master/migrate.go#L756) returns `os.ErrNotExist` (message "file does not exist") instead of the original error message (printed above).

It will be much easier to troubleshoot, if the original error with descriptive message is returned.

**Comment by francisdb** [comment]
is this a duplicate of #35?

**Comment by Kigamba** [comment]
Any solution on this issue?? I need to run the migrations every time the application starts. I keep getting this error if the migrations are up-to-date

**Comment by justty** [comment]
I have this problem on windows,  but on linux its worked. I think it's related with the docker volume.

docker-compose.yml
```
version: '3.6'
services:
  db:
    image: postgres:11.2
    restart: always
    container_name: db
    networks:
      - db-network
    ports:
      - 5432:5432
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  db_migrations:
    image: migrate/migrate
    container_name: db_migrations
    networks:
      - db-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    command: -path=/migrations -database postgres://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME?sslmode=disable up
```
